# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python

env:
  - TOXENV=py35
  - TOXENV=py34
  - TOXENV=py33
  - TOXENV=py27
  - TOXENV=py26
  - TOXENV=pypy

# command to install dependencies, e.g. pip install -r requirements.txt
install:
  - pip install -U tox
  - pip install -U coveralls
  - pip install -U flake8
  - pip install -U pytest
  - pip install -U pytest-xdist
  - pip install -U pytest-capturelog

before_script:
  - flake8 homebrew -v

# command to run tests, e.g. python setup.py test
script:
  - tox
  - coverage run --source=homebrew setup.py test

after_success:
  - coveralls

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: Iwan.in.t.Groen
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: igroen/homebrew
    condition: $TOXENV == py27
