dist: xenial
language: python
python: 3.7
before_script:
- flake8 homebrew -v
after_success:
- coveralls
- codecov
deploy:
  provider: pypi
  user: Iwan.in.t.Groen
  password:
    secure: XqBzNoifH4d0edIzh8cSm130k8Sderbbg2MNlwfqLQ0u8GrgEzDWK68FMrDq80foSY+N9AWZiv5aWl72+XijwOVgondX7nxXOwEMTFrUx8Iq/MQGMoZq9WLYTnKHb66Rc3tr9m0npqw9xX4IuYUGHAZzNqfYA4AvEG1w8DfMtvAz/8kGbiu2s/bKvVED/fAXvMfLdlysVXEJSfe4HyFu5L60SqDpSfg2+cQeoGhKUnI+SCVjIsi3HRPItGei9x1tAk5lGFEZkZSos7CIZcOdzOAOB4zJkywVZoHQc9ROh2yfSr7ZVCKvOSRYDRJTchC0+vt+iKks4EiLj/GkXD2xSJbtVuFTPiDZvx88+la4qVbhkknZ2GoBVUPmWkE1blnoPv9zNkIcgMSPboFWC+SbOEToTXAuO/qz3xx2g4FpJbPIA8QupKjgOa+d2PLX8/eePco1MMnTmFeumRU7i41rjmgsdYk0f7sugNzzxv1zs2vGBm2QCJYk48/uquRVtyA7GPkZqk5l1SlUaW02+n04cN1LPZ4jzTtZm1zq9AxYgroAHIU6p/3IUy6+npmeajFYHNP2uSndS8wqhH5UIsonlvhyNVUmk3MjM1HOAIMORptztVdAnkhj5bok4RmJQRYMHikKxo4XdGVh4aBgaYg4owzw/y0M/+QtLK6964z5p1w=
  on:
    repo: igroen/homebrew
    tags: true
  distributions: sdist bdist_wheel
env:
- TOXENV=py37
install:
- pip install -U tox
- pip install -U coveralls
- pip install -U pytest-cov
- pip install -U pytest-capturelog
- pip install -U flake8
- pip install -U codecov
script:
- tox
- py.test --cov=homebrew tests/
